/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class padec_natpsi_NativeMeth */

#ifndef _Included_padec_natpsi_NativeMeth
#define _Included_padec_natpsi_NativeMeth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     padec_natpsi_NativeMeth
 * Method:    singleInputServer
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_padec_natpsi_NativeMeth_singleInputServer
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     padec_natpsi_NativeMeth
 * Method:    singleInputClient
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_padec_natpsi_NativeMeth_singleInputClient
  (JNIEnv *, jobject, jint);

/*
 * Class:     padec_natpsi_NativeMeth
 * Method:    multiInputServer
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_padec_natpsi_NativeMeth_multiInputServer
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     padec_natpsi_NativeMeth
 * Method:    multiInputClient
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_padec_natpsi_NativeMeth_multiInputClient
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
